### ISSUE TITLE
Roadmap for production app

### ISSUE THREAD

**Issue by ethanfrey** [cosmos/cosmos-ledger#3]
We have gotten end-to-end functionality working now up to signing with basecli. However, it is all still more prototype stage.  Let's look at the current state and decide a roadmap of what is needed for release, now that it is clear it works.

Current:
* Go code panics when trying to use ledger keys if it is not plugged in properly. Due to limitations of go-crypto interface.
* New key generated every time you start cosmos app, cannot be reproduced

Desired:
* Solid error handling in golang (message, not panic)
* Cosmos app key is derived from ledger secret, stable, reproduceable on recovery
* Do we want to have multiple keys/wallets possible on the ledger?

Proposal, step one:
* Cosmos ledger app derives an initial wallet key from the ledger secret with a hardcoded cosmos path, index 0.  This key is used to sign all requests, but is stable, it becomes useful to store currency

Step two:
* Extend cosmos API to accept an index parameter in each sign request
* It will derive the private key from the ledger secret, cosmos hardcoded path, and the given index, then sign (and return public key as now)
* The cli allows creating multiple keys on the ledger, must keep track of which indexes are used
* Bringing ledger to a new computer means, user must re-add those keys by specifying the index

Step three:
* Require a user input on the ledger to trigger the signing (this is great for clients, not desired for server?  maybe some sort of build flag to make two apps)
* App is built and available for download via some app manager (no docker nonsense needed to install it, no warnings about non-genuine apps) -> this is packaging for release
* Bringing ledger to new computer means the cli would check the first N keys and query their accounts on the blockchain to see if they are used at all, storing those that seem to be interesting
* CLI can manage multiple ledgers also, associating stored keys with a ledger ID and an index
* CLI notifies which keys are usable, which need another ledger attached, helpful error messages

Please add other things that are needed, or other ideas of what to do.

**Comment by zramsay** [comment]
https://github.com/cosmos/ledger-cosmos/issues/15
