### ISSUE TITLE
Design: Architecture

### ISSUE THREAD

**Issue by adrianbrink** [cosmos/cosmos-ledger#7]
Thoughts:
* Library written in go-lang that communicates with the ledger
* UI only communicates through gaia
* Library integrated into gaia binary

Maybe this library should be written in Rust or C so that other zones can reuse it.

**Comment by zmanian** [comment]
We should try to minimze c in our stack cause vulnerabilities.

Gaia should talk to the Ledger daemon over a socket.

**Comment by adrianbrink** [comment]
For reference: https://github.com/cosmos/cosmos-sdk/issues/379

**Comment by zramsay** [comment]
https://github.com/cosmos/ledger-cosmos/issues/14
